global:
  namespace: demo-app

frontend:
  replicaCount: 2
  image:
    repository: ugardi/demo-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: demo-app.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

backend:
  replicaCount: 2
  image:
    repository: ugardi/demo-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

postgresql:
  enabled: true
  fullnameOverride: "demo-app-postgresql"
  auth:
    postgresPassword: "postgres123"
    database: "demoapp"
    username: "postgres"
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "demo-app.local"
      paths:
        - path: /
          pathType: Prefix
  tls: []


# global:
#   namespace: demo-app

# frontend:
#   replicaCount: 2
#   image:
#     repository: ugardi/demo-frontend
#     tag: latest
#     pullPolicy: Always
#   service:
#     type: ClusterIP
#     port: 80
#   ingress:
#     enabled: true
#     className: nginx
#     hosts:
#       - host: demo-app.local
#         paths:
#           - path: /
#             pathType: Prefix
#     tls: []
#   resources:
#     requests:
#       memory: "64Mi"
#       cpu: "50m"
#     limits:
#       memory: "128Mi"
#       cpu: "100m"

# backend:
#   replicaCount: 2
#   image:
#     repository: ugardi/demo-backend
#     tag: latest
#     pullPolicy: Always
#   service:
#     type: ClusterIP
#     port: 3001
#   env:
#     DB_HOST: "demo-app-postgresql"
#     DB_PORT: 5432
#     DB_NAME: "demoapp"
#     DB_USER: "postgres"
#   resources:
#     requests:
#       memory: "128Mi"
#       cpu: "100m"
#     limits:
#       memory: "256Mi"
#       cpu: "200m"

# postgresql:
#   enabled: true
#   auth:
#     postgresPassword: "postgres123"
#     database: "demoapp"
#   persistence:
#     enabled: true
#     size: 8Gi
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "100m"
#     limits:
#       memory: "512Mi"
#       cpu: "200m"

# ingress:
#   enabled: true
#   className: "nginx"
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   hosts:
#     - host: "demo-app.local"
#       paths:
#         - path: /
#           pathType: Prefix
#   tls: []