apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugardi/argocd-kubernetes-demo-app.git 
    targetRevision: HEAD
    path: helm/demo-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.replicas
